### PR TITLE
Add routing to a rails 4.1 app

### LINKED ISSUE #19: Rails 4.1 routes
I tried using Kilt in a Rails 4.1 RC1 application.  Everything worked except for one thing:  no routes were inserted into the application.

I think the problem is here:

https://github.com/AsheAvenue/Kilt/blob/1127de996a91bea8a6d5d0d453f21513b4fc71ec/lib/generators/kilt/backend_generator.rb#L15

``` ruby
inject_into_file Rails.root.join('config', 'routes.rb'), "\n\tmount Kilt::Engine => '/admin', as: 'kilt_engine'\n", :after => "#{Rails.application.class.parent_name.camelize}::Application.routes.draw do\n"      
```

The first line of my Rails 4.1 route file is:

``` ruby
Rails.application.routes.draw do
```

And my project name was "Blah".

Perhaps there should be a version check... or perhaps a call can be made for both the 4.0 and the 4.1 way.

### PR DESCRIPTION
**Pull request by darrencauthon**
This should resolve #19.

MacVim

### CODE REVIEW

**Comment by timboisvert** [comment]
Seems like it'd be a lot safer to inject it after ".routes.draw do", otherwise we risk breaking 4.0 installations. Unless of course we want to make 4.1 a requirement.

**Comment by darrencauthon** [comment]
I appended this 4.1 line after the 4.0 line. It won't append anything if it can't find an exact match, so the two lines can co-exist. 

But it definitely makes more sense to take one swipe instead of two. I'll try the ".routes.draw do" and verify it works. 
—

**Comment by darrencauthon** [comment]
I made this change, and it worked.

twitter-1

**Comment by darrencauthon** [comment]
Covered in #27

**Pull request closed without merging**
