### PR TITLE
Put the types in the menu.

### PR DESCRIPTION
**Pull request by darrencauthon**
Just my thoughts, as someone who has worked with a few dozen RefineryCMS apps...

The default behavior of the menu might be to make an entry for each type that a user might create.  The default dashboard could still provide that same navigation, but it will more likely be used to display some sort of "overall" information or message to a user.

yawn

### CODE REVIEW

**Comment by timboisvert** [comment]
This is awesome. We had a task for it but it looks like you've beaten us to it! Our original concern was the case when there are more than a half-dozen object types and it spills over. Heath was thinking about doing a drop-down menu for the types. This is great, though, so we'll use this. 

Tim

**Comment by darrencauthon** [comment]
I was thinking that, too, that there would be too many items to fit in the menu.  But I think that's where the simplicity of the framework works in its favor.  Just let the items wrap to two lines?

I wouldn't worry too much about it beyond that... it's a perfect solution for what I guess the majority of the apps will be.  I could use Kilt in about five apps today and I wouldn't have more than 5-6 tabs.

Just whatever happens, don't use the left-right scrolling arrow that's in RefineryCMS... I hate that thing.

**Comment by timboisvert** [comment]
I ended up having it use Kilt.types.each instead of @types.each so we don't have to keep the @types variable around.

**Comment by darrencauthon** [comment]
Sounds fine to me.  

Just a FYI:  I don't care if you take a pull request, alter it, or ignore it... they're just my way to communicate a thought or suggestion from afar.  :smile:

**Comment by darrencauthon** [comment]
I did the same thing, too.... I used a private member to thread variables through for something... then I thought it's simpler in the code to just call the kilt helpers. I just squashed them into one commit.

**Pull request merged**
